Project/Project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/mainapp/urls.py
from django.conf.urls import url
from django.urls import path

from mainapp import views

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),

    path('feedback/<int:pk>', views.FeedbackView.as_view(), name='feedback'),

    path('info/', views.InfoView.as_view(), name='info'),

    path('home/', views.HomeView.as_view(), name='home'),

    path('offer/<int:pk>', views.OfferView.as_view(), name='offer'),

    path('offer/<int:pk>/questions/', views.OfferQuestionsView.as_view(), name='question_list'),

    path('offer/<int:pk>/questions/create/', views.OfferQuestionCreate.as_view(), name='question_form'),

    path('response/<int:pk>', views.OfferResponseView.as_view(), name='response_detail'),

    url(r'^offer/response/(?P<pk>\d+)$', views.OfferResponseCreate, name='response_form'),

    path('employer/<int:pk>', views.OfferListByEmployerView.as_view(), name='offer_list_by_employer'),

    path('offer/<int:pk>/response/getall', views.ResponseListForOffer.as_view(), name='response_list_for_offer'),

    path('search/', views.OfferSearchListView.as_view(), name='offer_search_list_view'),

    url(r'^offer/delete/(?P<pk>\d+)$', views.offerDelete, name='offer_delete'),

    url(r'^offer/edit/(?P<pk>\d+)$', views.offerEdit, name='offer_edit'),

    url(r'^employer/edit/(?P<pk>\d+)$', views.employerEdit, name='employer_edit'),

    url(r'^question/delete/(?P<pk>\d+)$', views.questionDelete, name='question_delete'),

    url(r'^offer/new/$', views.NewOffer, name='newoffer'),

    url(r'^signin/$', views.UserFormView, name='signin'),

    url(r'^user/login$', views.LogIn, name='login'),

]

Project/mainapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Employer(models.Model):
    companyName = models.CharField(max_length=50)
    user = models.OneToOneField(User, related_name='employer', on_delete=models.CASCADE, null=True, )
    description = models.TextField()
    def __str__(self):
        return self.companyName
    def get_absolute_url(self):
        return reverse('offer_list_by_employer', args=[str(self.id)])



class Offer(models.Model):
    company = models.ForeignKey(Employer, models.CASCADE)
    position = models.CharField(max_length=50)
    branch = models.CharField(max_length=50, default="Inne")
    description = models.TextField()
    startDate = models.DateTimeField()
    endDate = models.DateTimeField()
    def get_url(self):
        return reverse('offer', args=[str(self.id)])
    def __str__(self):
        return "%s: %s " %(self.company.companyName, self.position)



class Question(models.Model):
    offer = models.ForeignKey(Offer, models.CASCADE)
    text = models.TextField(max_length=1000, verbose_name=('Pytanie'))
    def __str__(self):
        return "%s: %s " %(self.offer, self.text[:50])



class Form(models.Model):
    offer = models.ForeignKey(Offer, models.CASCADE)
    forename = models.CharField(max_length=50, verbose_name=('Imię'))
    surname = models.CharField(max_length=50, verbose_name=('Nazwisko'))
    email = models.CharField(max_length=50, verbose_name=('Adres email'))
    phoneNumber = models.CharField(max_length=50, verbose_name=('Numer telefonu'))
    answer = models.TextField(verbose_name=('Odpowiedź'));

    file = models.FileField(upload_to='documents/')
    def __str__(self):
        return "%s %s" %(self.forename, self.surname)

Project/mainapp/forms.py
from captcha.fields import CaptchaField
from django import forms

from .models import Offer, Employer, Form


class OfferForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Offer
        fields = ('position', 'description', 'branch')
        labels = {
            'position': 'Stanowisko',
            'description': 'Opis stanowiska',
            'branch': 'Branża'
        }



class EmployerForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Employer
        fields = ('companyName', 'description')
        labels = {
            'companyName': 'Nazwa firmy',
            'description': 'Opis firmy',
        }


from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    passwordConfirm = forms.CharField(widget=forms.PasswordInput)
    labels = {
        'password': 'Hasło',
        'passwordConfirm': 'Powtórz hasło',
    }
    def clean_passwordConfirm(self):
        if 'password' in self.cleaned_data:
            password = self.cleaned_data['password']
            passwordConfirm = self.cleaned_data['passwordConfirm']
            if password == passwordConfirm:
                return passwordConfirm

        raise forms.ValidationError('Hasła różnią się.')


    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'passwordConfirm')
        labels = {
            'username': 'Login',
            'email': 'Adres email',
            'password': 'Hasło',
            'passwordConfirm': 'Powtórz hasło'
        }


class OfferResponseForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Form
        fields = ('forename', 'surname', 'email', 'phoneNumber', 'answer', 'file')
        labels = {
            'forename': 'Imię',
            'surname': 'Nazwisko',
            'email': 'Adres Email',
            'phoneNumber': 'Numer telefonu',
            'answer': 'Odpowiedź',
            'file': 'CV',
        }

Project/mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView

from Project import settings
from .models import *
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import OfferForm, UserForm, EmployerForm, OfferResponseForm
from django.views.generic.edit import CreateView
from django.urls import reverse


# strona główna - można przejść do dodawania oferty lub przeglądania ofert
# lista pracodawców
class IndexView(ListView):
    template_name = 'mainapp/index.html'
    model = Employer


# lista wszystkich ofert
class HomeView(ListView):
    model = Offer
    template_name = 'mainapp/home.html'


# informacja o pomyślnym dodaniu odpowiedzi na formularz
class FeedbackView(DetailView):
    template_name = 'mainapp/feedback.html'
    model = Offer
    def get_object(self):
        return get_object_or_404(Offer, pk=self.kwargs.get("pk"))

# informacja o pakiecie VIP
class InfoView(ListView):
    template_name = 'mainapp/info.html'
    model = Offer

# Wyświetlenie szczeółów oferty
class OfferView(DetailView):
    model = Offer
    template_name = 'mainapp/offer.html'

    def get_object(self):
        return get_object_or_404(Offer, pk=self.kwargs.get("pk"))

# Szczegółowy widok pracodawcy, wyświetla listę ofert przez niego dodaną
class OfferListByEmployerView(ListView):
    model = Offer
    template_name = 'mainapp/offer_list_by_employer.html'

    # lista ofert dodana przez danego usera
    def get_queryset(self):
        id = self.kwargs['pk']
        target_employer = get_object_or_404(Employer, pk=id)
        return Offer.objects.filter(company=target_employer)

    # dodanie informacji o pracodawcy żeby można było je wyświetlić
    def get_context_data(self, **kwargs):
        context = super(OfferListByEmployerView, self).get_context_data(**kwargs)
        context['employer'] = get_object_or_404(Employer, pk=self.kwargs['pk'])
        return context


# Wyświetlenie listy odpowiedzi na ofertę
@method_decorator(login_required, name='dispatch')
class ResponseListForOffer(ListView):
    model = Form
    template_name = 'mainapp/response_list_for_offer.html'

    def get_queryset(self):
        id = self.kwargs['pk']
        target_offer = get_object_or_404(Offer, pk=id)
        return Form.objects.filter(offer=target_offer)

    def get_context_data(self, **kwargs):
        context = super(ResponseListForOffer, self).get_context_data(**kwargs)
        context['offer'] = get_object_or_404(Offer, pk=self.kwargs['pk'])
        return context


# Wyswietla liste pytań danej oferty
@method_decorator(login_required, name='dispatch')
class OfferQuestionsView(DetailView):
    model = Offer
    template_name = 'mainapp/question_list.html'
    def get_object(self):
        return get_object_or_404(Offer, pk=self.kwargs.get("pk"))




#Dodawanie pytania do oferty
@method_decorator(login_required, name='dispatch')
class OfferQuestionCreate(CreateView):
    model = Question
    fields = ['text', ]

    def get_context_data(self, **kwargs):
        context = super(OfferQuestionCreate, self).get_context_data(**kwargs)
        context['offer'] = get_object_or_404(Offer, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):

        form.instance.offer= get_object_or_404(Offer, pk=self.kwargs['pk'])
        return super(OfferQuestionCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('question_list', kwargs={'pk': self.kwargs['pk'], })


# Wyswietla szczegóły odpowiedzi na ofertę
@method_decorator(login_required, name='dispatch')
class OfferResponseView(DetailView):
    model = Form
    template_name = 'mainapp/response_detail.html'
    def get_object(self):
        return get_object_or_404(Form, pk=self.kwargs.get("pk"))




def OfferResponseCreate(request, pk):
    offer = get_object_or_404(Offer, pk=pk)
    if request.method == 'POST':
        form = OfferResponseForm(request.POST, request.FILES)
        if form.is_valid():

            form.instance.offer = get_object_or_404(Offer, pk=pk)
            form.save()
            message = 'Odpowiedź została dodana'

            subject = "Do Twojej oferty dodano nową odpowiedź !"
            emailMessage = "Ktoś dodał aplikację na stanowisko " + offer.position
            send_mail(subject, emailMessage, settings.EMAIL_HOST_USER, [offer.company.user.email], fail_silently=True)

            return render(request, 'mainapp/info.html', {'templateText': message})
    else:
        form = OfferResponseForm()
    return render(request, 'mainapp/form_form.html', {
        'form': form, 'offer': offer})

# Dodawanie nowej oferty
@login_required
def NewOffer(request):
    if request.method == "POST":

        form = OfferForm(request.POST)
        if form.is_valid():
            offer = form.save(commit=False)
            offer.startDate = timezone.now()
            offer.endDate = timezone.now()
            offer.company = Employer.objects.get(user=request.user)
            offer.save()
            return redirect('question_list', pk=offer.pk)
    else:
        form = OfferForm()
    return render(request, 'mainapp/newoffer.html', {'form': form})


# Dodawanie nowego użytkownika
def UserFormView(request):
    if request.method == "POST":
        user_form = UserForm(request.POST)
        emp_form = EmployerForm(request.POST)
        if emp_form.is_valid() and user_form.is_valid():
            user = user_form.save(commit=False)
            emp = emp_form.save(commit=False)
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password']
            user.set_password(password)
            user.save()
            emp.user = user
            emp.save()
            subject = 'Dziękujemy za zarejestrowanie konta!'
            message = 'Od teraz możesz korzystać w pełni z naszego portalu pracy!\n \n Twoje dane:\n\t-Login: '
            message += username
            message += '\n\t-Hasło: '
            message += password
            message += '\n\nPamiętaj, aby nikomu nie udostępniać swoich danych!\n\nPozdrawiam\nAdministrator Portalu Pracy'
            send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email], fail_silently=True)
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('index')

            return redirect('index')
    else:
        user_form = UserForm()
        emp_form = EmployerForm()
    return render(request, 'mainapp/signin.html', {'user_form': user_form, 'emp_form': emp_form})



# Wyszukiwanie
from functools import reduce
import operator
from django.db.models import Q
class OfferSearchListView(HomeView):
    def get_queryset(self):
        result = super(OfferSearchListView, self).get_queryset()

        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(branch__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(position__icontains=q) for q in query_list))
            )
        return result


@login_required
def offerDelete(request, pk):
    offer = get_object_or_404(Offer, pk=pk)
    if offer.company.user != request.user:
        message = 'Odmowa dostępu!'
        return render(request, 'mainapp/info.html', {'templateText': message})
    if request.method == 'POST':
        offer.delete()
        message = 'Oferta została usunięta.'
        return render(request, 'mainapp/info.html', {'templateText': message})
    return render(request, 'mainapp/delete_confirmation.html')

@login_required
def offerEdit(request, pk):
    message = 'Edycja oferty'
    offer = get_object_or_404(Offer, pk=pk)
    if offer.company.user != request.user:
        message = 'Odmowa dostępu'
        return render(request, 'mainapp/info.html',
                      {'templateText': message})

    form = OfferForm(request.POST or None, instance=offer)
    if form.is_valid():
        form.save()
        return redirect('question_list', pk=offer.pk)
    return render(request, 'mainapp/newoffer.html', {'form': form, 'message': message})


@login_required
def employerEdit(request, pk):
    message = 'Edycja profilu'
    employer = get_object_or_404(Employer, pk=pk)
    if employer.user != request.user:
        message = 'Odmowa dostępu.'
        return render(request, 'mainapp/info.html', {'templateText': message})

    form = EmployerForm(request.POST or None, instance=employer)
    if form.is_valid():
        form.save()
        return redirect('offer_list_by_employer', pk=employer.pk)
    return render(request, 'mainapp/employer_edit.html', {'form': form, 'message': message})


@login_required
def questionDelete(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if question.offer.company.user != request.user:
        message = 'Brak dostępu'
        return render(request, 'mainapp/info.html', {'templateText': message})
    if request.method == 'POST':
        question.delete()
        return redirect('question_list', pk=question.offer.pk)
    text = 'pytanie'
    return render(request, 'mainapp/delete_confirmation.html', {'text':text})


# Logowanie
def LogIn(request):
    form = UserForm()
    return render(request, 'mainapp/../templates/registration/login.html', {'form': form})

Project/templates/mainapp/delete_confirmation.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Portal Pracy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>

</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="container-box">
        <div class="navbar-header">
            <a class="btn-menu" href="{% url 'index' %}">Portal Pracy</a>
            <a class="btn-menu" href="{% url 'home' %}">Oferty</a>
            {% if user.is_authenticated %}
                 <a class="btn-menu" href="{% url 'newoffer' %}">Dodaj ofertę</a>
            {% endif %}
            {% if user.is_authenticated %}
                    <a class="btn-menu" href="{% url 'logout' %}?next={{request.path}}">Wyloguj się: {{ user.get_username }}</a>
                    <a class="btn-menu" href="{% url 'info' %}">Profil</a>
                {% else %}
                    <a class="btn-menu" href="{% url 'login' %}?next={{request.path}}">Zaloguj się</a>
                {% endif %}
        </div>
    </div>
</div>

<div class="jumbotron" ; content="width=device-width">
    <div align="center" class="container">
         <form method="post">{% csrf_token %}
             <br>
		     <p> Usuwanie danych wymaga potwierdzenia</p>
             <input type="submit" class="btn-main" value="Potwierdź" />
         </form>
         <br>
         <a href="{% url 'index' %}" class="btn-main">Powrót do strony głównej</a>
    </div>
</div>
</body>
</html>

Project/templates/mainapp/form_form.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Portal Pracy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>
    <style>
        .jumbotron {
            background-color: white;
            color: gray();
        }

    </style>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'index' %}">Portal Pracy</a>
            <a class="navbar-brand" href="{% url 'home' %}">Oferty</a>
            {% if user.is_authenticated %}
                 <a class="navbar-brand" href="{% url 'newoffer' %}">Dodaj ofertę</a>
            {% endif %}
        </div>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'logout' %}?next={{request.path}}">Wyloguj się: {{ user.get_username }}</a>
                    <a class="navbar-brand" href="{% url 'offer_list_by_employer' user.employer.pk %}">Profil</a>
                {% else %}
                    <a class="navbar-brand" href="{% url 'login' %}?next={{request.path}}">Zaloguj się</a>
                {% endif %}
            </ul>
    </div>
</div>
<div class="jumbotron" ; content="width=device-width">
<div class="container-newoffer">
    <div class="container" align="center">
         <h2>Odpowiedź na ofertę {{ offer }}</h2>
         <div class="panel panel-default">
            <div class="panel-body">
                <ul>
                {% for question in offer.question_set.all %}
                    <p>{{ question.text }}</p>
                {% endfor %}
                </ul>
            </div>
         </div>
         <form action="" method="post"  enctype="multipart/form-data"﻿ >
            {% csrf_token %}
            <table>
            {{ form.as_table }}
            </table>
             <div class="container-btns" aria-label="Basic example">
                 <button class='captcha-refresh btn-main' style="margin-right: 10px">Odśwież</button>
                 <button type="submit" class="btn-main" style="margin-right: 10px; width: 50%">Zatwierdź</button>
                 <a href="{% url 'index' %}" style="width: 50%"><button class="btn-main">Powrót</button></a>
             </div>
        </form>
        <br>
    </div>
</div>
</div>
</body>
</html>

Project/templates/mainapp/offer_list_by_employer.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Portal Pracy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />

  </head>
  <body>
<div class="navbar navbar-fixed-top">
    <div class="container-box">
        <div class="navbar-header">
            <a class="btn-menu" href="{% url 'index' %}">Portal Pracy</a>
            <a class="btn-menu" href="{% url 'home' %}">Oferty</a>
            {% if user.is_authenticated %}
                 <a class="btn-menu" href="{% url 'newoffer' %}">Dodaj ofertę</a>
            {% endif %}
            {% if user.is_authenticated %}
                    <a class="btn-menu" href="{% url 'logout' %}?next={{request.path}}">Wyloguj się: {{ user.get_username }}</a>
                    <a class="btn-menu" href="{% url 'info' %}">Profil</a>
                {% else %}
                    <a class="btn-menu" href="{% url 'login' %}?next={{request.path}}">Zaloguj się</a>
                {% endif %}
        </div>
    </div>
</div>

  <div class="jumbotron">
         <div class="container">
            <h1>{{employer.companyName}}
            {% if user.is_authenticated and user == employer.user %}
                <a href="{% url 'employer_edit' employer.pk %}">
                  <h2 class="glyphicon glyphicon-edit"></h2>
                </a>
            {% endif %}
            </h1>
             <div class="employer-description">
                    <p class="lead">{{ employer.description }}</p>
            </div>
            {% if object_list %}
            <ul>
                {% for offer in offer_list %}
                    <li>
                        <div style="margin-top: 10px">
                            <a href="{% url 'offer' offer.pk %}" class="btn-main">{{offer.position}}</a>
                        </div>

                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <div>
                        <a class="btn-main" href="{% url 'index' %}" style="margin-top: 15px">Brak ofert do wyświetlenia</a>
                </div>
            {% endif %}
         </div>
    </div>

  </body>
</html>

Project/templates/mainapp/question_list.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <title>Portal Pracy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>

</head>
<body>
<div class="navbar navbar-fixed-top">
    <div class="container-box">
        <div class="navbar-header">
            <a class="btn-menu" href="{% url 'index' %}">Portal Pracy</a>
            <a class="btn-menu" href="{% url 'home' %}">Oferty</a>
            {% if user.is_authenticated %}
                 <a class="btn-menu" href="{% url 'newoffer' %}">Dodaj ofertę</a>
            {% endif %}
            {% if user.is_authenticated %}
                    <a class="btn-menu" href="{% url 'logout' %}?next={{request.path}}">Wyloguj się: {{ user.get_username }}</a>
                    <a class="btn-menu" href="{% url 'info' %}">Profil</a>
                {% else %}
                    <a class="btn-menu" href="{% url 'login' %}?next={{request.path}}">Zaloguj się</a>
                {% endif %}
        </div>
    </div>
</div>

<div class="jumbotron" content="width=device-width">
    <div class="container">
        <br>
            <h1>Pytania do tej oferty</h1>
            <ul>
                {% for question in offer.question_set.all %}
                    <hr>
                    <p>{{ question.text }}</p>
                {% endfor %}
            </ul>
        <br>
        <a href="{% url 'question_form' offer.id %}" class="btn-main">Dodaj nowe pytanie</a>
        <br>
        <a href="{% url 'offer' offer.id %}" class="btn-main" >Zakończ dodawanie oferty</a>
    </div>
</div>
</body>
</html>

Project/templates/mainapp/response_list_for_offer.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Portal Pracy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>

  </head>
  <body>

<div class="navbar navbar-fixed-top">
    <div class="container-box">
        <div class="navbar-header">
            <a class="btn-menu" href="{% url 'index' %}">Portal Pracy</a>
            <a class="btn-menu" href="{% url 'home' %}">Oferty</a>
            {% if user.is_authenticated %}
                 <a class="btn-menu" href="{% url 'newoffer' %}">Dodaj ofertę</a>
            {% endif %}
            {% if user.is_authenticated %}
                    <a class="btn-menu" href="{% url 'logout' %}?next={{request.path}}">Wyloguj się: {{ user.get_username }}</a>
                    <a class="btn-menu" href="{% url 'info' %}">Profil</a>
                {% else %}
                    <a class="btn-menu" href="{% url 'login' %}?next={{request.path}}">Zaloguj się</a>
                {% endif %}
        </div>
    </div>
</div>

  <div class="jumbotron">
         <div class="container">
             <div>
            <h1>{{offer.company.companyName}}: {{ offer.position}}</h1>
             <div class="panel panel-default">
                <div class="panel-body">
                    <p class="lead">{{offer.description }}</p>
                </div>
            </div>
            {% if object_list %}
            <ul>
                {% for form in form_list %}
                    <li>
                        <div align="center">
                            <a href="{% url 'response_detail' form.pk %}"class="btn-main">
                                {{form.forename}} {{ form.surname }}
                            </a>
                        </div>

                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <div>
                    <h3>Brak odpowiedzi na ofertę.</h3>
                    <a href="{% url 'index' %}" class="btn-main">Powrót</a>
                </div>

            {% endif %}
                 </div>
         </div>
    </div>
  </body>
</html>